### ISSUE TITLE
Problem submitting isolation-pvp

### ISSUE THREAD

**Issue by jganzabal** [udacity/AIND-Isolation#21]
When I try to submit isolation-pvp I get an error about an import I am not importing in my competition_agent.py file

$ udacity submit isolation-pvp

NOTICE:

  You are about to submit your agent.  If you have previously submitted
  your agent, continuing will replace that submission.

Please type 'yes' to confirm submission>yes

Submission includes the following files:
    competition_agent.py

Uploading submission...
[=========================== 100% ===========================] 13217/13217

Waiting for results...Done!

Results:
--------
-1. Test imports & calls:                                              
    AssertionError: No module named 'workspace.game_agent' -- module import failed.

Details are available in isolation-pvp-result-4836.json.

If you would like this version of the project to be reviewed,
submit isolation-pvp-4836.zip to the reviews website.

The json file result file looks like this:
**isolation-pvp-result-xxxx.json**
"Uh-oh, I could not find your game_agent.py file.\n"

**Comment by pritamps** [comment]
Hey,

Is your code named `competition_agent.py`? The assistant needs a file called `game_agent.py` to run the tests. That might be the issue 👍 

-Pritam

**Comment by cgearhart** [comment]
The isolation-pvp endpoint on the PA hasn't been completed yet, so the feedback is nonsense. I probably won't have time to get it up and running for a bit yet. There will be an announcement when we start accepting submissions for the April folks,
