### ISSUE TITLE
Tournament code should be multithreaded

### ISSUE THREAD

**Issue by sunsided** [udacity/AIND-Isolation#22]
When experimenting with new heuristics functions, most of the time is spent waiting on the `tournament.py` to finish, which takes ages even with a low amount of games (e.g. the default `5`). Since it doesnt even appear to be CPU bound, evaluating matches in parallel would massively increase productivity.

**Comment by cgearhart** [comment]
Have a look at the experimental branch implementing multiprocessing for the tournament: https://github.com/udacity/AIND-Isolation/tree/xMultiProcessing

It hasn't been tested on Windows, and I won't have much time to support it for awhile (hence marking it "experimental"), but it should be most of the way there.

**Comment by sunsided** [comment]
Very nice! Thanks!
